version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    # volumes:
    #   - ./backend:/app
      # - ./ontology:/ontology
    ports:
      - "8001:8001"
    depends_on:
      - fuseki

  fuseki:
    image: stain/jena-fuseki
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=admin
    volumes:
      - ./ontology:/fuseki-data